services:
  api:
    build: .
    container_name: rafdi-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:IbFHPrOSOcIxSqqzFhCeinyURzhAhoiU@caboose.proxy.rlwy.net:44999/railway
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8
    container_name: rafdi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rafdi
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: